# Generated by Django 5.1.7 on 2025-03-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='category_id',
        ),
    ]
