# Generated by Django 5.1.7 on 2025-03-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_category_news_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
