# Generated by Django 5.1.7 on 2025-03-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_article_id_comment_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('commentbase_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.commentbase')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
            bases=('api.commentbase',),
        ),
    ]
