# Generated by Django 5.1.7 on 2025-03-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='api.commentbase'),
        ),
    ]
